### PR TITLE
Change from direct email link to not to reduce spam

### PR DESCRIPTION
**Pull request by katamaritaco**
Is this even reasonable?

### CODE REVIEW

**Comment by LOZORD** [comment]
I think an image or obfuscated text (without `mailto`) would be better.

**Comment by katamaritaco** [comment]
You're probably right - as long as there is something

**Comment by mjneil** [comment]
Did you still want the mailto: in the href? (it currently is there) Also the coords.html has our emails was well in the href, if we don't want that there it should be changed too

**Comment by Ricky54326** [comment]
Is this the new site? Or old? Because current site actually does not do this if you look in the source.

**Comment by LOZORD** [comment]
How's [this](
http://latex2png.com/output//latex_7e5ea67e6900b547a6d1e3f317e9e902.png)? I
used latex2png.com.

**Comment by Zenchreal** [comment]
The hyphen looks wrong, but otherwise that looks nice.

**Comment by katamaritaco** [comment]
Please only use Comic Sans or :scroll: Papyrus :scroll:

**Comment by katamaritaco** [comment]
@LOZORD if you want to bring the image in lsometime, make a new PR.

**Comment by LOZORD** [comment]
Didn't see the separated `-at-` before. Unless we get more spam then we normally do, LGTM.

**Pull request merged**
