### PR TITLE
Improve the events page

### PR DESCRIPTION
**Pull request by zthomae**
I'm working on making the events page better. The following things are done so far:

1. Events are separated into past and upcoming. This is done as the events.json file is processed. The intention is that once an event is added with a proper date, moving it from "upcoming" to "past" should require no maintenance. Notice that there are currently no upcoming events, and 
1. I replaced the lorem ipsum with some dummy real events (Leo's talks from this fall). It seems reasonable that all of the events from the [talks repo](https://github.com/UW-UPL/Talks) could be included at some point.
1. I removed the redundant showing of the date when there is no event image. This was admittedly arbitrary, but I didn't see the purpose in including this, and it made the page messier.
1. I moved the date handling into the events service. Dates should now be parsed correctly (assuming they're all formatted the same, which I think we can enforce on ourselves). Events are also now sorted in different orders: upcoming events should be sorted soonest-first, but previous events should be sorted most-recent first.

Things that haven't been done yet, but should be:

1. Separate events into categories. Right now I only included talks because those are the only events with reliable dates that I have access to.
1. Improve the markup. I hacked it together.
1. Style the page elements. I didn't do this at all.
1. Make my angular code less bad.

### CODE REVIEW

**Comment by mjneil** [comment]
The idea was the redundant date was gonna be styled like a little calendar date the same size the image would be to keep a consistent look. Open to other ideas tho

**Comment by zthomae** [comment]
I think the page might look best with neither calendar widgets nor images. Especially since, if we want to include things that aren't relevant to every event (for example, youtube videos of talks), we might not have much consistency anyway.

**Comment by zthomae** [comment]
I've tried my best to handle date parsing more correctly. Details are in the top post.

**Comment by LOZORD** [comment]
Would Unix timestamps work? :laughing:

**Comment by LOZORD** [comment]
Or perhaps something like:
```json
"datetime": {
  "date": {
    "month": 2,
    "day": 18,
    "year": 2016
  },
  "time": {
    "hour": 19,
    "minute": 0
  }
}
```

Notice the __24__ hour time (instead of 12).

**Comment by zthomae** [comment]
That would make the implementation simpler, but I'm not sure if future UPLers would prefer working with that over a formatted string.

**Comment by mjneil** [comment]
I don't think you need to make the date parsing so complicated, I'm cool with creating the nice lookkng date string in the events service, however parsing the string yourself and creating the date object is pointless and makes it look confusing. No need for a regex. JavaScript's date object parses the date string given into a date object, all that regex parsing is extra unneeded work

**Comment by mjneil** [comment]
I still disagree with the image thing. The plans I had for styling the page would really benefit from having that spot..I just haven't had a chance to get to it yet

**Comment by zthomae** [comment]
The reason I redid the date parsing is because the date parsing didn't work (as in, it parsed to the wrong dates).

**Comment by mjneil** [comment]
What dates caused that?

**Comment by katamaritaco** [comment]
regex r :100: fun

**Comment by zthomae** [comment]
I got rid of the regular expressions, because I found the problems in the original. `getDay()`, which gets the day of the week instead of the day of the month, was being called when it shouldn't have been (`getDate()` is the function you want). I may have overreacted a bit...

I think this date handling is still better than the master branch because the real work is done in proper JS (where we can debug things) instead of in the template.

**Comment by mjneil** [comment]
I definitely agree I like having all the work in the factory over the controller and template. But ya, the getDay/getDate was definitely a my bad, the regex was definitely overkill. I'll take closer look at things when I get to an actual computer and can sit down with it.

**Comment by katamaritaco** [comment]
@mjneil Only code reviews from :phone: :iphone:  are :ok_hand: , :no_entry_sign: :computer: s. :sob:

**Comment by zthomae** [comment]
I fixed the conflicts with master. Hopefully this can be merged soon so fixing conflicts doesn't become a problem.

And just so we're clear, the date format we're using appears to be supported in browsers, but isn't in the [language standard](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-date-time-string-format). Regular expressions are probably more cautious than we need to be, but I always commit incrementally :+1: :ok_hand: :100:

**Pull request merged**
