### PR TITLE
Added Leon's Hours

### PR DESCRIPTION
**Pull request by lwdinh**

### CODE REVIEW

**Comment by LOZORD** [comment]
Please be careful not to add Windows line endings `^M`.
__OR__
Does anyone know how to remove Windows line endings without nuking the file?

**Comment by melutzke** [comment]
Why does the line endings thing matter to anyone who isn't Karen? Is there an actual reason?

**Comment by LOZORD** [comment]
It is a form of unnec. whitespace -- ergo est malum :sunglasses:

**Comment by melutzke** [comment]
So you're bothered by invisible control characters that are reasonably handled by both platforms :^) ?

**Comment by LOZORD** [comment]
Exactly. `^M` is the molemen of code :alien:

**Comment by Ricky54326** [comment]
Sublime Text has an option to switch to Unix line endings, btw, even on Windows. For the future.

**Pull request merged**
