### PR TITLE
Lab data

### PR DESCRIPTION
**Pull request by Squeakrats**
Added lab.yaml for basic lab information.

### CODE REVIEW

**Comment by Ricky54326** [comment]
Idk man I think this PR is way too big, you should break it down into 3 or 4 separate ones. And make sure you get 2-6 code reviewers too but other than that lgtm 👍

**Comment by zthomae** [comment]
Shouldn't there be a notice over winter break as well?

Also, for what it's worth, I think it might be easier to remember to update this if it were in `hours.yaml`.

**Comment by Squeakrats** [comment]
Good point. I'll modify the message to be more general.

**Comment by zthomae** [comment]
I don't think I qualify as a reviewer anymore, and can't do this myself, but I think someone should merge this.

**Comment by LOZORD** [comment]
Lol that works :man_shrugging:

**Pull request merged**
